redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\Home\\Desktop\\Porrrrjeccct\\Proiect-Farmacie\\lambda"
functionsDirectoryOrigin = "config-v1"
headers = []

[dev]
command = "npm run start-mock-server"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Home\\Desktop\\Porrrrjeccct\\Proiect-Farmacie"
publishOrigin = "default"
command = "npm run build"
commandOrigin = "config"
functions = "C:\\Users\\Home\\Desktop\\Porrrrjeccct\\Proiect-Farmacie\\lambda"

[build.environment]
PORT = 3002.0

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]